### ISSUE TITLE
Layout FIGMA do projeto - Incluir barra de busca de jogos

### ISSUE THREAD

**Issue by Fbueno12** [Fbueno12/projeto-repogames#4]

**Comment by Fbueno12** [comment]
inclui a barra de busca na área do menu lateral

https://www.figma.com/proto/fchplKNp15XfHouFMHEDyd/Vers%C3%A3o-WEB-0.1?node-id=1%3A2&scaling=contain

**Comment by leosoulmon** [comment]
Aprovado

**Comment by leosoulmon** [comment]
aprovado
